/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Alat;
import model.Inzenjer;
import model.Lokacija;
import model.Masina;
import model.TipMasine;
import model.Upotreba;

/**
 *
 * @author vldmrk
 */
public class MasinaForma extends javax.swing.JDialog {

    private Controller cont = Controller.getInstance();
    private Inzenjer inz;

    /**
     * Creates new form Test
     */
    public MasinaForma(java.awt.Frame parent, boolean modal, Inzenjer inz) {
        super(parent, modal);
        initComponents();
        this.inz = inz;
        popuni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProizvodjac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldGodProiz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxLokacija = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTip = new javax.swing.JComboBox<>();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRadniVek = new javax.swing.JTextField();
        jComboBoxAlati = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButtonDodajAlat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUpotreba = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabelInzenjer = new javax.swing.JLabel();
        jButtonObrisiMasinu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv");

        jTextFieldDatum.setText("2025-11-11");

        jLabel2.setText("Godina proizvodnje");

        jTextFieldProizvodjac.setText("asdf");

        jLabel3.setText("Datum pocetka");

        jTextFieldGodProiz.setText("2001");

        jLabel4.setText("Tip masine");

        jLabel5.setText("Lokacija");

        jButtonSacuvaj.setText("SACUVAJ MASINU");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel6.setText("Proizvodjac");

        jTextFieldNaziv.setText("asdf");

        jLabel7.setText("Radni vek");

        jTextFieldRadniVek.setText("20");
        jTextFieldRadniVek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRadniVekActionPerformed(evt);
            }
        });

        jLabel8.setText("Alat");

        jButtonDodajAlat.setText("Dodaj alat");
        jButtonDodajAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajAlatActionPerformed(evt);
            }
        });

        jTableUpotreba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableUpotreba);

        jLabel9.setText("Korisnik: ");

        jLabelInzenjer.setText("jLabel10");

        jButtonObrisiMasinu.setText("OBRISI MASINU");
        jButtonObrisiMasinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiMasinuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxAlati, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDatum)
                    .addComponent(jTextFieldGodProiz, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jTextFieldProizvodjac, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jComboBoxLokacija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jTextFieldRadniVek, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDodajAlat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelInzenjer, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisiMasinu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelInzenjer))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldRadniVek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldGodProiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAlati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jButtonDodajAlat))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButtonObrisiMasinu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        JOptionPane.showMessageDialog(this, "USPESNO DODATE MASINE", "USPEH", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonDodajAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajAlatActionPerformed

        Lokacija lok = (Lokacija) jComboBoxLokacija.getSelectedItem();
        if (!cont.proveriLok(lok)) {
            JOptionPane.showMessageDialog(this, "VEC POSTOJI MASINA OVDE", "IMA MASINA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int godProiz = Integer.valueOf(jTextFieldGodProiz.getText());
        if (godProiz < 1900 || godProiz > 2024) {
            JOptionPane.showMessageDialog(this, "NEISPRAVNA GODINA", "GODINA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Random rand = new Random();
        Date datumPoc = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-mm-dd");
        try {
            datumPoc = format.parse(jTextFieldDatum.getText());
        } catch (ParseException ex) {
            Logger.getLogger(MasinaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (datumPoc.before(new Date())) {
            JOptionPane.showMessageDialog(this, "LOS DATUM SI ODABRAO", "DATUM", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String naziv = jTextFieldNaziv.getText();
        String proizvodjac = jTextFieldProizvodjac.getText();
        int radniVek = Integer.valueOf(jTextFieldRadniVek.getText());

        TipMasine tip = (TipMasine) jComboBoxTip.getSelectedItem();

        Masina m = new Masina(rand.nextInt(9999999), naziv, proizvodjac, radniVek, godProiz, datumPoc, tip, lok);
        cont.dodajMasinu(m);
        Alat a = (Alat) jComboBoxAlati.getSelectedItem();
        Upotreba u = new Upotreba(rand.nextInt(9999999), a, m);
        cont.dodajUpotrebu(u);
        cont.oduzmiStanje(u.getAlat().getId());
        popuni();
    }//GEN-LAST:event_jButtonDodajAlatActionPerformed

    private void jButtonObrisiMasinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiMasinuActionPerformed
        int selekRed = jTableUpotreba.getSelectedRow();
        if (selekRed == -1) {
            JOptionPane.showMessageDialog(this, "MORAS DA OZNACIS RED", "OZNACI RED", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleUpotreba mtu = (ModelTabeleUpotreba) jTableUpotreba.getModel();
        int id = mtu.getUpotrebe().get(selekRed).getId();
        int alatId = mtu.getUpotrebe().get(selekRed).getAlat().getId();
        cont.dodajStanje(alatId);
        cont.obrisiUpotrebu(id);
        cont.obrisiMasinu(id);
        popuni();
    }//GEN-LAST:event_jButtonObrisiMasinuActionPerformed

    private void jTextFieldRadniVekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRadniVekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRadniVekActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajAlat;
    private javax.swing.JButton jButtonObrisiMasinu;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Alat> jComboBoxAlati;
    private javax.swing.JComboBox<Lokacija> jComboBoxLokacija;
    private javax.swing.JComboBox<TipMasine> jComboBoxTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInzenjer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableUpotreba;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldGodProiz;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldProizvodjac;
    private javax.swing.JTextField jTextFieldRadniVek;
    // End of variables declaration//GEN-END:variables

    private void popuni() {
        jLabelInzenjer.setText(inz.toString());

        ModelTabeleUpotreba mta = new ModelTabeleUpotreba();
        jTableUpotreba.setModel(mta);

        List<Lokacija> lokacije = cont.vratuListuLokacija();

        for (Lokacija l : lokacije) {
            jComboBoxLokacija.addItem(l);
        }

        List<Alat> alati = cont.vratiListuAlata();
        for (Alat a : alati) {
            jComboBoxAlati.addItem(a);
        }

        TipMasine[] tipovi = TipMasine.values();
        Arrays.sort(tipovi, (a, b) -> a.name().compareTo(b.name()));
        for (TipMasine t : tipovi) {
            jComboBoxTip.addItem(t);
        }
    }

}
